name: Update snippets

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 1 * *"

jobs:
  update-snippets:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout VS Code
        uses: actions/checkout@v6
        with:
          repository: microsoft/vscode
          path: vscode

      - name: Extract Snippets
        run: |
          set -euo pipefail
          chmod +x ./script.sh
          ./script.sh

      - name: Commit
        run: |
          set -euo pipefail

          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

          git add -A snippets package.json

          if git diff --cached --quiet; then
            echo "No changes, skipping commit"
            exit 0
          fi

          git commit -m "Update snippets"
          git pull --rebase origin main
          git push

    timeout-minutes: 10
